/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnalyticsDashboard: typeof import('./src/components/Analitics_Dashboard/AnalyticsDashboard.vue')['default']
    AnimatedTitle: typeof import('./src/components/Animated_title/AnimatedTitle.vue')['default']
    CurrentActivity: typeof import('./src/components/My_current_activity/CurrentActivity.vue')['default']
    DivSlot: typeof import('./src/components/Helper_components/DivSlot.vue')['default']
    GamificationToast: typeof import('./src/components/Gamification/GamificationToast.vue')['default']
    GamificationWidget: typeof import('./src/components/Gamification/GamificationWidget.vue')['default']
    GitConstruction3D: typeof import('./src/components/Git_all/GitConstruction3D.vue')['default']
    GitHubStats: typeof import('./src/components/Git_all/GitHubStats.vue')['default']
    GitTimeMachine: typeof import('./src/components/Git_all/GitTimeMachine.vue')['default']
    GuidedTour: typeof import('./src/components/Guide_visit/GuidedTour.vue')['default']
    Loading: typeof import('./src/components/Helper_components/Loading.vue')['default']
    LogoSection: typeof import('./src/components/Helper_components/logoSection.vue')['default']
    MultiWorldClock: typeof import('./src/components/Helpers_api/MultiWorldClock.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    ProjectBossQuiz: typeof import('./src/components/Projects_room/ProjectBossQuiz.vue')['default']
    ProjectGallery: typeof import('./src/components/Projects_room/ProjectGallery.vue')['default']
    QRcode: typeof import('./src/components/Contact_room/QRcode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkillSection: typeof import('./src/components/Helper_components/SkillSection.vue')['default']
    Stack: typeof import('./src/components/technic_stack/stack.vue')['default']
    TechLogo: typeof import('./src/components/Helper_components/TechLogo.vue')['default']
  }
}
