/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimatedTitle: typeof import('./src/components/AnimatedTitle.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    LogoSection: typeof import('./src/components/logoSection.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    ProjectGallery: typeof import('./src/components/ProjectGallery.vue')['default']
    QRcode: typeof import('./src/components/QRcode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkillSection: typeof import('./src/components/SkillSection.vue')['default']
    TechLogo: typeof import('./src/components/TechLogo.vue')['default']
  }
}
