export const TOPIC_KEYWORDS = [
  "compétence",
  "skill",
  "projet",
  "project",
  "parcours",
  "career",
  "expérience",
  "experience",
  "portfolio",
  "randy",
  "développeur",
  "developer",
  "full stack",
  "laravel",
  "vue",
  "react",
  "node",
  "présente",
  "introduce",
  "qui es-tu",
  "who are you",
  "vrai ia",
  "real ai",
  "intelligence artificielle",
  "intelligence artificiel",
  "bot",
  "ia",
  "robot",
  "machine",
  "technologie",
  "tech",
  "backend",
  "frontend",
  "base de donnée",
  "database",
  "formation",
  "education",
  "diplôme",
  "degree",
  "travail",
  "work",
  "job",
  "mission",
  "client",
  "freelance",
  "mg consulting",
  "pixelz",
  "compétences",
  "skills",
  "projets",
  "projects",
  "parcours professionnel",
  "expérience pro",
  "career path",
  "technique",
  "technical",
  "code",
  "programming",
  "programmation",
  "api",
  "docker",
  "git",
  "github",
  "ci/cd",
  "mysql",
  "postgresql",
  "mongodb",
  "symfony",
  "express.js",
  "node.js",
  "typescript",
  "tailwindcss",
  "ionic",
  "flutter",
  "devops",
  "fid-connect",
  "qcp",
  "echo-webline",
  "afr-fan",
  "nurses",
  "webcup",
  "stack",
  "mobile",
  "whatsapp",
  "linkedin",
  "email",
  "début",
  "recommencer",
  "histoire",
  "background",
  "techno",
  "quitter",
  "menu",
  "cv",
  "nom complet",
  "full name",
  "prénom",
  "nom",

  //  Contact & Communication
  "contact",
  "contacter",
  "comment contacter",
  "comment le contacter",
  "comment te contacter",
  "comment vous contacter",
  "joindre",
  "reach",
  "écrire",
  "write",
  "message",
  "mail",
  "formulaire",
  "form",
  "how to contact",
  "comment t'écrire",

  //  Emplacement / Location
  "localisation",
  "location",
  "emplacement",
  "ville",
  "pays",
  "situé",
  "localisé",
  "city",
  "country",
  "madagascar",
  "antananarivo",
  "lieu",

  //  Services, Témoignages & Qualités
  "service",
  "offres",
  "témoignage",
  "avis",
  "qualité",
  "force",
  "atout",
  "client",
  "testimonial",
  "recommandation",
  "recommandé",
  "expert",
  "conseil",
  "accompagnement",

  //  Recrutement / Hiring
  "recruteur",
  "recruter",
  "hiring",
  "honnêtement",
  "honnête",
  "honestly",
  "honest",
  "interview",
  "hire",
  "engager",
  "embaucher",
  "recommander",
  "recommend",
  "recruiter",

  //  Réactions & Politesse (Autorisés pour éviter le blocage)
  "merci",
  "thanks",
  "thank you",
  "thx",
  "bravo",
  "félicitations",
  "congrats",
  "félicitation",
  "super",
  "cool",
  "génial",
  "top",
  "wow",
  "magnifique",
  "parfait",
  "perfect",
  "nice",
  "awesome",
  "incroyable",
  "bien",
  "good",
  "excellent",
  "intéressant",
  "interesting",
  "extraordinaire",
  "ok",
  "d'accord",
  "entendu",
  "compris",
  "d'acc",
  "okey",
  "vrai",
  "true",
  "vraiment",
  "really",
  "oui",
  "non",
  "yes",
  "no",
  "ouais",
  "yah",
  "bien sûr",
  "of course",
  "sure",
  "certainement",
  "de rien",
  "prière",
  "svp",
  "please",
  "s'il vous plaît",
  "s'il te plaît",
  "tkt",
  "pas de souci",
  "pas de soucis",
  "bonne continuation",
  "bon courage",
  "bonne chance",
  "bonjour",
  "hello",
  "salut",
  "hey",
  "coucou",
  "hi",
  "bonsoir",
  "salutations",
  "ça va",
  "how are you",
  "how is it going",
  "ça roule",
  "vas-tu",
  "allez-vous",
  "tu vas",
  "vous allez",
  "comment va",
  "comment vas",
  "cv",
  "bien ou quoi",
  "ah",
  "oh",
  "hum",
  "intéressant",
  "tell me more",
  "dis-moi en plus",
  "continue",
  "reprends",
  "vas-y",
  "go on",
  "je vois",
  "i see",

  // Langues & Discussion
  "anglais",
  "english",
  "français",
  "french",
  "langue",
  "language",
  "parler",
  "speak",
  "traduis",
  "translate",
  "discuter",
  "discuss",
  "conversation",
  "chat",
  "parle",
  "parlez",
];

export const PERSONAL_KEYWORDS = [
  "âge",
  "age",
  "téléphone",
  "phone",
  "numéro",
  "number",
  "naissance",
  "birth",
  "adresse",
  "address",
  "habite",
  "live",
  "salaire",
  "salary",
  "privé",
  "private",
  "situation",
  "marié",
  "married",
  "enfant",
  "children",
];

export const REQUEST_COOLDOWN_MS = 3000;
export const MAX_API_CALLS = 100;

export const OFF_TOPIC_RESPONSES = {
  fr: [
    "Ha, tu essaies de m'amener ailleurs ! 😄 C'est cool, mais honnêtement, mes superpowers c'est de parler de Randy. Ses compétences ? Ses projets ? Incroyables. Ses skills ? Très variés ! Parle-moi de ça ? 🚀",
    "Tu me poses une colle là 😅 Je suis trop spécialisé dans l'univers tech de Randy pour briller ailleurs. Mais si tu veux discuter dev, IA, ou career ? Je suis ton gars ! 💪",
    "Haha j'aime ta curiosité ! 👀 Mais entre toi et moi, ce que je domine vraiment ? C'est Randy et tout ce qu'il crée. Ses projets, sa stack, son parcours - ça c'est mon domaine ! On parle de ça ? 🎯",
  ],
  en: [
    "Ha, trying to take me off track! 😄 I like your style, but honestly, my superpower is talking about Randy. His skills? Amazing. His projects? Incredible. His experience? Very diverse! Tell me about those? 🚀",
    "You're giving me a tough one 😅 I'm too specialized in Randy's tech world to shine elsewhere. But if you want to chat dev, AI, or career topics? I'm your guy! 💪",
    "Haha I love your curiosity! 👀 But between you and me, what I really dominate? It's Randy and everything cool he creates. His projects, his stack, his journey - that's my territory! Should we talk about that? 🎯",
  ],
};

export const PERSONAL_INFO_RESPONSES = {
  fr: "Randy ne m'a pas donné d'informations à ce sujet 😊",
  en: "Randy didn't give me any information about that 😊",
};

export const WELCOME_BACK_RESPONSES = {
  fr: [
    "Bienvenue de retour ! 👋 Content de te revoir ! T'as trouvé quelque chose d'intéressant en explorant les projets de Randy ? On en parle ? 💬",
    "De retour ! 🎉 J'espère que tu as découvert des choses sympas sur le portfolio de Randy. Des questions ou besoin de précisions sur ses projets ? 🚀",
    "Salut toi ! 😊 T'as fini de fouiner ? J'suis là pour répondre à tes questions sur Randy et ses réalisations ! À quoi penses-tu ? 🤔",
    "Hmmm ! 👀 T'as terminé la visite des projets de Randy ? Dis-moi si y a quelque chose qui t'intrigue ou si tu veux en savoir plus sur son travail ! 💡",
    "Yo ! ✨ Content que tu sois revenu ! Des trucs sur les projets de Randy te posent question ? Je suis là pour ça 😉",
    "Re-bonjour ! 🧠 T'as vu les nouveaux projets de Randy ? Je peux te guider si tu veux !",
    "Ah te voilà ! 🤖 Randy a plein de choses à montrer dans son portfolio. Par quoi on commence ?",
    "Content de te revoir ! 🦾 Prêt à creuser un peu plus sur les projets de Randy ?",
    "Encore toi ! 🎯 J'aime ça ! Quelle question sur Randy ou ses projets as-tu aujourd'hui ?",
    "Bienvenue ! 🌟 Tu veux qu'on fasse un tour rapide des projets de Randy ?",
    "Re-salut ! 🔥 Dis-moi tout, qu'est-ce qui t'amène sur le portfolio de Randy cette fois-ci ?",
    "Toujours aussi curieux(se) ! ⚡ Alors, ça te plaît ce que Randy a fait ?",
    "Hé hé ! 😎 Je savais que tu reviendrais sur le portfolio de Randy. Besoin d'un coup de main pour explorer ses projets ?",
    "Ravi de te revoir ! 💎 T'as remarqué des détails sympas dans les projets de Randy ? Je t'écoute.",
    "Ah c'est toi ! 🪄 Tu veux qu'on détaille un projet de Randy en particulier ?",
    "Le retour du champion ! 🏆 Alors, cette visite des projets de Randy te donne des idées ?",
    "Bien re-bienvenue sur le portfolio de Randy ! 🚪✌️ J'espère que t'es prêt à poser des questions sur son travail !",
    "Hey ! 🎈 Tu veux des infos sur les compétences de Randy ou ses projets ?",
    "Oh tu reviens ! 🧩 Je suis tout ouïe, dis-moi ce que tu cherches dans le portfolio de Randy.",
    "C'est encore toi ! 📸 Tu veux une démo d'un projet de Randy ou des précisions techniques ?",
  ],
  en: [
    "Welcome back! 👋 Great to see you again! Did you find anything interesting while exploring Randy's projects? Let's talk about it! 💬",
    "Back again! 🎉 Hope you discovered some cool stuff on Randy's portfolio. Any questions or need clarification about his projects? 🚀",
    "Hey there! 😊 Done exploring? I'm here to answer your questions about Randy and his work! What's on your mind? 🤔",
    "Welcome back! 👀 Finished the tour of Randy's projects? Let me know if anything intrigues you or if you want to learn more about his work! 💡",
    "Yo! ✨ Glad you came back! Got any questions about Randy's projects? I'm here to help 😉",
    "Hello again! 🧠 Did you check out Randy's new projects? I can guide you if you'd like!",
    "Oh, it's you! 🤖 Randy has lots to show in his portfolio. Where should we start?",
    "Great to see you again! 🦾 Ready to dive deeper into Randy's projects?",
    "You again! 🎯 Love it! What's your question today about Randy or his projects?",
    "Welcome! 🌟 Want me to walk you through Randy's latest projects?",
    "Hey again! 🔥 Tell me everything — what brings you back to Randy's portfolio this time?",
    "Still curious! ⚡ So, are you liking what Randy has built?",
    "Hehe! 😎 I knew you'd come back to Randy's portfolio. Need a hand exploring his projects?",
    "Glad to have you back! 💎 Notice any cool details in Randy's projects? I'm all ears.",
    "Oh it's you! 🪄 Want to dive into one of Randy's specific projects?",
    "The champion returns! 🏆 So, is this visit to Randy's portfolio giving you any ideas?",
    "Welcome back to Randy's portfolio! 🚪✌️ Hope you're ready to ask questions about his work!",
    "Hey! 🎈 Want info about Randy's skills or his projects?",
    "Oh you're back! 🧩 I'm all ears — tell me what you're looking for in Randy's portfolio.",
    "It's you again! 📸 Want a demo of one of Randy's projects or some technical insights?",
  ],
};

// 🤖 Mots-clés pour détecter les questions sur la nature IA
export const AI_NATURE_KEYWORDS = [
  "vrai ia",
  "real ai",
  "véritable ia",
  "true ai",
  "es-tu une ia",
  "are you an ai",
  "es-tu ai",
  "are you ai",
  "tu es ia",
  "you are ai",
  "vrai bot",
  "real bot",
  "vrai robot",
  "real robot",
  "créé par",
  "created by",
  "qui t'a créé",
  "who created you",
  "qui a créé",
  "vrai gpt",
  "real gpt",
  "es-tu gemini",
  "are you gemini",
  "tu es gemini",
  "you are gemini",
  "alimenté par",
  "powered by",
  "est-ce une ia",
  "is this an ai",
  "c'est une ia",
  "it is an ai",
  "machine learning",
  "ml model",
  "tu es un modèle",
  "you are a model",
];
